package org.eason.workflowengine.domain.common.dao.impl.mysql;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.eason.workflowengine.domain.common.model.SequenceFlow;
import org.eason.workflowengine.domain.common.model.SequenceFlowExample;

public interface SequenceFlowMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int countByExample(SequenceFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int deleteByExample(SequenceFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int insert(SequenceFlow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int insertSelective(SequenceFlow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	List<SequenceFlow> selectByExample(SequenceFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	SequenceFlow selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByExampleSelective(@Param("record") SequenceFlow record,
			@Param("example") SequenceFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByExample(@Param("record") SequenceFlow record,
			@Param("example") SequenceFlowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByPrimaryKeySelective(SequenceFlow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByPrimaryKey(SequenceFlow record);
}