package org.eason.workflowengine.domain.common.dao.impl.mysql;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.eason.workflowengine.domain.common.model.Task;
import org.eason.workflowengine.domain.common.model.TaskExample;
import org.eason.workflowengine.domain.common.model.TaskWithBLOBs;

public interface TaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int countByExample(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int deleteByExample(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int insert(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int insertSelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	List<Task> selectByExampleWithBLOBs(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	List<Task> selectByExample(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	Task selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Task record,
			@Param("example") TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") Task record,
			@Param("example") TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByExample(@Param("record") Task record,
			@Param("example") TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByPrimaryKeySelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByPrimaryKey(Task record);
}