package org.eason.workflowengine.domain.common.dao.impl.mysql;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.eason.workflowengine.domain.common.model.Workflow;
import org.eason.workflowengine.domain.common.model.WorkflowExample;

public interface WorkflowMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int countByExample(WorkflowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int deleteByExample(WorkflowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int insert(Workflow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int insertSelective(Workflow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	List<Workflow> selectByExample(WorkflowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	Workflow selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Workflow record,
			@Param("example") WorkflowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByExample(@Param("record") Workflow record,
			@Param("example") WorkflowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByPrimaryKeySelective(Workflow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	int updateByPrimaryKey(Workflow record);
}