package org.eason.workflowengine.domain.common.model;

import java.util.ArrayList;
import java.util.List;

public class SequenceFlowExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public SequenceFlowExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdIsNull() {
			addCriterion("workflow_Id is null");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdIsNotNull() {
			addCriterion("workflow_Id is not null");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdEqualTo(Long value) {
			addCriterion("workflow_Id =", value, "workflowId");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdNotEqualTo(Long value) {
			addCriterion("workflow_Id <>", value, "workflowId");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdGreaterThan(Long value) {
			addCriterion("workflow_Id >", value, "workflowId");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdGreaterThanOrEqualTo(Long value) {
			addCriterion("workflow_Id >=", value, "workflowId");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdLessThan(Long value) {
			addCriterion("workflow_Id <", value, "workflowId");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdLessThanOrEqualTo(Long value) {
			addCriterion("workflow_Id <=", value, "workflowId");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdIn(List<Long> values) {
			addCriterion("workflow_Id in", values, "workflowId");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdNotIn(List<Long> values) {
			addCriterion("workflow_Id not in", values, "workflowId");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdBetween(Long value1, Long value2) {
			addCriterion("workflow_Id between", value1, value2, "workflowId");
			return (Criteria) this;
		}

		public Criteria andWorkflowIdNotBetween(Long value1, Long value2) {
			addCriterion("workflow_Id not between", value1, value2,
					"workflowId");
			return (Criteria) this;
		}

		public Criteria andFromTaskIsNull() {
			addCriterion("from_task is null");
			return (Criteria) this;
		}

		public Criteria andFromTaskIsNotNull() {
			addCriterion("from_task is not null");
			return (Criteria) this;
		}

		public Criteria andFromTaskEqualTo(String value) {
			addCriterion("from_task =", value, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskNotEqualTo(String value) {
			addCriterion("from_task <>", value, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskGreaterThan(String value) {
			addCriterion("from_task >", value, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskGreaterThanOrEqualTo(String value) {
			addCriterion("from_task >=", value, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskLessThan(String value) {
			addCriterion("from_task <", value, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskLessThanOrEqualTo(String value) {
			addCriterion("from_task <=", value, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskLike(String value) {
			addCriterion("from_task like", value, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskNotLike(String value) {
			addCriterion("from_task not like", value, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskIn(List<String> values) {
			addCriterion("from_task in", values, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskNotIn(List<String> values) {
			addCriterion("from_task not in", values, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskBetween(String value1, String value2) {
			addCriterion("from_task between", value1, value2, "fromTask");
			return (Criteria) this;
		}

		public Criteria andFromTaskNotBetween(String value1, String value2) {
			addCriterion("from_task not between", value1, value2, "fromTask");
			return (Criteria) this;
		}

		public Criteria andToTaskIsNull() {
			addCriterion("to_task is null");
			return (Criteria) this;
		}

		public Criteria andToTaskIsNotNull() {
			addCriterion("to_task is not null");
			return (Criteria) this;
		}

		public Criteria andToTaskEqualTo(String value) {
			addCriterion("to_task =", value, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskNotEqualTo(String value) {
			addCriterion("to_task <>", value, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskGreaterThan(String value) {
			addCriterion("to_task >", value, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskGreaterThanOrEqualTo(String value) {
			addCriterion("to_task >=", value, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskLessThan(String value) {
			addCriterion("to_task <", value, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskLessThanOrEqualTo(String value) {
			addCriterion("to_task <=", value, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskLike(String value) {
			addCriterion("to_task like", value, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskNotLike(String value) {
			addCriterion("to_task not like", value, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskIn(List<String> values) {
			addCriterion("to_task in", values, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskNotIn(List<String> values) {
			addCriterion("to_task not in", values, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskBetween(String value1, String value2) {
			addCriterion("to_task between", value1, value2, "toTask");
			return (Criteria) this;
		}

		public Criteria andToTaskNotBetween(String value1, String value2) {
			addCriterion("to_task not between", value1, value2, "toTask");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeIsNull() {
			addCriterion("interval_time is null");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeIsNotNull() {
			addCriterion("interval_time is not null");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeEqualTo(Long value) {
			addCriterion("interval_time =", value, "intervalTime");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeNotEqualTo(Long value) {
			addCriterion("interval_time <>", value, "intervalTime");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeGreaterThan(Long value) {
			addCriterion("interval_time >", value, "intervalTime");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("interval_time >=", value, "intervalTime");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeLessThan(Long value) {
			addCriterion("interval_time <", value, "intervalTime");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeLessThanOrEqualTo(Long value) {
			addCriterion("interval_time <=", value, "intervalTime");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeIn(List<Long> values) {
			addCriterion("interval_time in", values, "intervalTime");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeNotIn(List<Long> values) {
			addCriterion("interval_time not in", values, "intervalTime");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeBetween(Long value1, Long value2) {
			addCriterion("interval_time between", value1, value2,
					"intervalTime");
			return (Criteria) this;
		}

		public Criteria andIntervalTimeNotBetween(Long value1, Long value2) {
			addCriterion("interval_time not between", value1, value2,
					"intervalTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Long value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Long value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Long value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Long value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Long> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Long> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Long value1, Long value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sequence_flow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sequence_flow
     *
     * @mbggenerated do_not_delete_during_merge Sat Feb 21 10:58:27 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}