package org.eason.workflowengine.domain.common.model;

public class Task {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.workflow_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long workflowId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.name
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.type
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.timeout
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Integer timeout;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.status
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.create_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.queued_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long queuedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.dispatch_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long dispatchTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.start_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.end_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.timeout_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long timeoutTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.callback_endpoint
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String callbackEndpoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.data
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String data;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.id
	 * @return  the value of task.id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.id
	 * @param id  the value for task.id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.workflow_id
	 * @return  the value of task.workflow_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getWorkflowId() {
		return workflowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.workflow_id
	 * @param workflowId  the value for task.workflow_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setWorkflowId(Long workflowId) {
		this.workflowId = workflowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.name
	 * @return  the value of task.name
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.name
	 * @param name  the value for task.name
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.type
	 * @return  the value of task.type
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.type
	 * @param type  the value for task.type
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.timeout
	 * @return  the value of task.timeout
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Integer getTimeout() {
		return timeout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.timeout
	 * @param timeout  the value for task.timeout
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setTimeout(Integer timeout) {
		this.timeout = timeout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.status
	 * @return  the value of task.status
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.status
	 * @param status  the value for task.status
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.create_time
	 * @return  the value of task.create_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.create_time
	 * @param createTime  the value for task.create_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.queued_time
	 * @return  the value of task.queued_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getQueuedTime() {
		return queuedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.queued_time
	 * @param queuedTime  the value for task.queued_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setQueuedTime(Long queuedTime) {
		this.queuedTime = queuedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.dispatch_time
	 * @return  the value of task.dispatch_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getDispatchTime() {
		return dispatchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.dispatch_time
	 * @param dispatchTime  the value for task.dispatch_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setDispatchTime(Long dispatchTime) {
		this.dispatchTime = dispatchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.start_time
	 * @return  the value of task.start_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.start_time
	 * @param startTime  the value for task.start_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.end_time
	 * @return  the value of task.end_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.end_time
	 * @param endTime  the value for task.end_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setEndTime(Long endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.timeout_time
	 * @return  the value of task.timeout_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getTimeoutTime() {
		return timeoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.timeout_time
	 * @param timeoutTime  the value for task.timeout_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setTimeoutTime(Long timeoutTime) {
		this.timeoutTime = timeoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.callback_endpoint
	 * @return  the value of task.callback_endpoint
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getCallbackEndpoint() {
		return callbackEndpoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.callback_endpoint
	 * @param callbackEndpoint  the value for task.callback_endpoint
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setCallbackEndpoint(String callbackEndpoint) {
		this.callbackEndpoint = callbackEndpoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.data
	 * @return  the value of task.data
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getData() {
		return data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.data
	 * @param data  the value for task.data
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setData(String data) {
		this.data = data;
	}
}