package org.eason.workflowengine.domain.common.model;

public class TaskEvent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_event.id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_event.task_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_event.workflow_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long workflowId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_event.name
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_event.event_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long eventTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_event.create_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_event.data
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String data;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_event.id
	 * @return  the value of task_event.id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_event.id
	 * @param id  the value for task_event.id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_event.task_id
	 * @return  the value of task_event.task_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_event.task_id
	 * @param taskId  the value for task_event.task_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_event.workflow_id
	 * @return  the value of task_event.workflow_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getWorkflowId() {
		return workflowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_event.workflow_id
	 * @param workflowId  the value for task_event.workflow_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setWorkflowId(Long workflowId) {
		this.workflowId = workflowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_event.name
	 * @return  the value of task_event.name
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_event.name
	 * @param name  the value for task_event.name
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_event.event_time
	 * @return  the value of task_event.event_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getEventTime() {
		return eventTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_event.event_time
	 * @param eventTime  the value for task_event.event_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setEventTime(Long eventTime) {
		this.eventTime = eventTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_event.create_time
	 * @return  the value of task_event.create_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_event.create_time
	 * @param createTime  the value for task_event.create_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_event.data
	 * @return  the value of task_event.data
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getData() {
		return data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_event.data
	 * @param data  the value for task_event.data
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setData(String data) {
		this.data = data;
	}
}