package org.eason.workflowengine.domain.common.model;

import java.util.ArrayList;
import java.util.List;

public class WorkflowExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public WorkflowExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("app_id is null");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("app_id is not null");
			return (Criteria) this;
		}

		public Criteria andAppIdEqualTo(String value) {
			addCriterion("app_id =", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotEqualTo(String value) {
			addCriterion("app_id <>", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThan(String value) {
			addCriterion("app_id >", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(String value) {
			addCriterion("app_id >=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThan(String value) {
			addCriterion("app_id <", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThanOrEqualTo(String value) {
			addCriterion("app_id <=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLike(String value) {
			addCriterion("app_id like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotLike(String value) {
			addCriterion("app_id not like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdIn(List<String> values) {
			addCriterion("app_id in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotIn(List<String> values) {
			addCriterion("app_id not in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdBetween(String value1, String value2) {
			addCriterion("app_id between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotBetween(String value1, String value2) {
			addCriterion("app_id not between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueIsNull() {
			addCriterion("app_task_queue is null");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueIsNotNull() {
			addCriterion("app_task_queue is not null");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueEqualTo(String value) {
			addCriterion("app_task_queue =", value, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueNotEqualTo(String value) {
			addCriterion("app_task_queue <>", value, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueGreaterThan(String value) {
			addCriterion("app_task_queue >", value, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueGreaterThanOrEqualTo(String value) {
			addCriterion("app_task_queue >=", value, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueLessThan(String value) {
			addCriterion("app_task_queue <", value, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueLessThanOrEqualTo(String value) {
			addCriterion("app_task_queue <=", value, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueLike(String value) {
			addCriterion("app_task_queue like", value, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueNotLike(String value) {
			addCriterion("app_task_queue not like", value, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueIn(List<String> values) {
			addCriterion("app_task_queue in", values, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueNotIn(List<String> values) {
			addCriterion("app_task_queue not in", values, "appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueBetween(String value1, String value2) {
			addCriterion("app_task_queue between", value1, value2,
					"appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andAppTaskQueueNotBetween(String value1, String value2) {
			addCriterion("app_task_queue not between", value1, value2,
					"appTaskQueue");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Long value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Long value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Long value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Long value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Long> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Long> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Long value1, Long value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeIsNull() {
			addCriterion("scheduled_start_time is null");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeIsNotNull() {
			addCriterion("scheduled_start_time is not null");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeEqualTo(Long value) {
			addCriterion("scheduled_start_time =", value, "scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeNotEqualTo(Long value) {
			addCriterion("scheduled_start_time <>", value, "scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeGreaterThan(Long value) {
			addCriterion("scheduled_start_time >", value, "scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("scheduled_start_time >=", value, "scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeLessThan(Long value) {
			addCriterion("scheduled_start_time <", value, "scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeLessThanOrEqualTo(Long value) {
			addCriterion("scheduled_start_time <=", value, "scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeIn(List<Long> values) {
			addCriterion("scheduled_start_time in", values,
					"scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeNotIn(List<Long> values) {
			addCriterion("scheduled_start_time not in", values,
					"scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeBetween(Long value1, Long value2) {
			addCriterion("scheduled_start_time between", value1, value2,
					"scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andScheduledStartTimeNotBetween(Long value1, Long value2) {
			addCriterion("scheduled_start_time not between", value1, value2,
					"scheduledStartTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeIsNull() {
			addCriterion("dispatch_time is null");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeIsNotNull() {
			addCriterion("dispatch_time is not null");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeEqualTo(Long value) {
			addCriterion("dispatch_time =", value, "dispatchTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeNotEqualTo(Long value) {
			addCriterion("dispatch_time <>", value, "dispatchTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeGreaterThan(Long value) {
			addCriterion("dispatch_time >", value, "dispatchTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("dispatch_time >=", value, "dispatchTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeLessThan(Long value) {
			addCriterion("dispatch_time <", value, "dispatchTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeLessThanOrEqualTo(Long value) {
			addCriterion("dispatch_time <=", value, "dispatchTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeIn(List<Long> values) {
			addCriterion("dispatch_time in", values, "dispatchTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeNotIn(List<Long> values) {
			addCriterion("dispatch_time not in", values, "dispatchTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeBetween(Long value1, Long value2) {
			addCriterion("dispatch_time between", value1, value2,
					"dispatchTime");
			return (Criteria) this;
		}

		public Criteria andDispatchTimeNotBetween(Long value1, Long value2) {
			addCriterion("dispatch_time not between", value1, value2,
					"dispatchTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("start_time is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("start_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Long value) {
			addCriterion("start_time =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Long value) {
			addCriterion("start_time <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Long value) {
			addCriterion("start_time >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("start_time >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Long value) {
			addCriterion("start_time <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Long value) {
			addCriterion("start_time <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Long> values) {
			addCriterion("start_time in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Long> values) {
			addCriterion("start_time not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Long value1, Long value2) {
			addCriterion("start_time between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Long value1, Long value2) {
			addCriterion("start_time not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Long value) {
			addCriterion("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Long value) {
			addCriterion("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Long value) {
			addCriterion("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Long value) {
			addCriterion("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Long value) {
			addCriterion("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Long> values) {
			addCriterion("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Long> values) {
			addCriterion("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Long value1, Long value2) {
			addCriterion("end_time between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Long value1, Long value2) {
			addCriterion("end_time not between", value1, value2, "endTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table workflow
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table workflow
     *
     * @mbggenerated do_not_delete_during_merge Sat Feb 21 10:58:27 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}