package org.eason.workflowengine.domain.common.model;

public class Workflow {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.name
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.status
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.app_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.app_task_queue
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private String appTaskQueue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.create_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.scheduled_start_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long scheduledStartTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.dispatch_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long dispatchTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.start_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflow.end_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	private Long endTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.id
	 * @return  the value of workflow.id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.id
	 * @param id  the value for workflow.id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.name
	 * @return  the value of workflow.name
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.name
	 * @param name  the value for workflow.name
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.status
	 * @return  the value of workflow.status
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.status
	 * @param status  the value for workflow.status
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.app_id
	 * @return  the value of workflow.app_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.app_id
	 * @param appId  the value for workflow.app_id
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.app_task_queue
	 * @return  the value of workflow.app_task_queue
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public String getAppTaskQueue() {
		return appTaskQueue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.app_task_queue
	 * @param appTaskQueue  the value for workflow.app_task_queue
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setAppTaskQueue(String appTaskQueue) {
		this.appTaskQueue = appTaskQueue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.create_time
	 * @return  the value of workflow.create_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.create_time
	 * @param createTime  the value for workflow.create_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.scheduled_start_time
	 * @return  the value of workflow.scheduled_start_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getScheduledStartTime() {
		return scheduledStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.scheduled_start_time
	 * @param scheduledStartTime  the value for workflow.scheduled_start_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setScheduledStartTime(Long scheduledStartTime) {
		this.scheduledStartTime = scheduledStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.dispatch_time
	 * @return  the value of workflow.dispatch_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getDispatchTime() {
		return dispatchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.dispatch_time
	 * @param dispatchTime  the value for workflow.dispatch_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setDispatchTime(Long dispatchTime) {
		this.dispatchTime = dispatchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.start_time
	 * @return  the value of workflow.start_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.start_time
	 * @param startTime  the value for workflow.start_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflow.end_time
	 * @return  the value of workflow.end_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public Long getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflow.end_time
	 * @param endTime  the value for workflow.end_time
	 * @mbggenerated  Mon Feb 23 20:44:45 CST 2015
	 */
	public void setEndTime(Long endTime) {
		this.endTime = endTime;
	}
}